# Generated by Django 3.1.7 on 2021-05-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210510_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activelisting',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='description',
            field=models.CharField(max_length=356),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='image',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/495px-No-Image-Placeholder.svg.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='activelisting',
            name='shortDescription',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
